### ISSUE TITLE
My xbox account

### ISSUE THREAD

**Issue by vBIackbeardv** [r6db/frontend#13]
I don't even exist in the database and I don't have a new account I've had my account since the beginning of last season. My xbox account is v BIackbeard v ..... It is spelled with a the letter "i" for a "l". when i go to the the actual rainbow six website it pops up fine but on here it says i dont exist. Please can you guys help me..

**Comment by LaxisB** [comment]
yeah, currently our jobs are not running, and neither new or old accounts are updating.
@NaughtyMuppet is currently working on it. 

we had to move all servers quite suddenly since the ps4 server was failing

**Comment by NaughtyMuppet** [comment]
Fixed stats now, update tasks are running, should be fixed in the next few hours

**Comment by NaughtyMuppet** [comment]
Fixed a lot of issues thanks to this usecase, thanks.

https://r6db.com/player/db778463-1c77-4856-89d1-e2f6ceb8a768
