### ISSUE TITLE
[Suggestion] Adding color gradient in Operators page stats

### ISSUE THREAD

**Issue by LaxisB** [r6db/frontend#3]
by @GoldMath

Hello,

A quick suggestion for the Operators page in extended view, is that possible to add a color gradient for "win ratio" "k/d ratio". 

This would improve quick reading of Pros/Cons. 

Exemple: Highlight all Win Ratio under 48% in red and green over 54%. Over 1.20 k/d in Green, lower that 0.80 in red,... (values to be confirmed)

Maybe make the threshold customizable or even toggleable on/off.
Adding the operators icons in the name column would be a nice addition too.

![example](http://i.imgur.com/cElks1M.jpg)

Regards,

**Comment by laxisb** [comment]
added gradients; still missing op icons

**Comment by GoldMath** [comment]
I can upload all operators icons. Should I upload them in: _frontend/src/assets/op_icons/_
Is the .png format good for you?

**Comment by laxisb** [comment]
we have a spritesheet with most of them at `src/assets/operators.png`.
i was hoping to find svg versions for them, sice those are usually smaller and easier to scale.
@NaughtyMuppet also made a spreadhseet at some point, so i can copy that if i don't find svg versions

**Comment by laxisb** [comment]
found the css 87415c7f49b5113e22f370e20b09be77535c5b82/src/app/components/Pages/Detail/detail.scss#L222

**Comment by GoldMath** [comment]
> i was hoping to find **svg** versions for them
[All Operators to Red Crow](https://drive.google.com/file/d/0BxYzSiVtQSX8c005WWZDZTcyQXM/)
[Velvet Shell](http://svgshare.com/i/f1.svg)
[Blood Orchid](https://drive.google.com/file/d/0BxYzSiVtQSX8cDFybXc0T05hdHM/)

**Comment by laxisb** [comment]
ooh boy, you're making me moist.
i'll start adding those tomorrow then.

**Comment by GoldMath** [comment]
There is a huge gap in the Win Ratio gradient, almost 20% just for the yellow; around 40% to 60%

I suggest: 
red: 0-38% / orange: 38-48% / yellow: 48-58% / green: +58%

**Comment by LaxisB** [comment]
the scales are currently 0.5x, 0.8x, 1.2x and 1.5x
https://github.com/r6db/frontend/blob/develop/src/app/components/misc/Scale/index.js#L10

feel free to adjust them a bit. i'll merge into master in the meantime

**Comment by GoldMath** [comment]
I'm not unable to make testing locally. 
I can only make a guess on these values or make you push 50 merges to see myself lol

Any idea how I could try some editing on my side?

**Comment by LaxisB** [comment]
it should set up the the standard way
- git clone
- yarn
- yarn start
- -> localhost:9000  
  
it proxies to the actual website for api requests

**Comment by GoldMath** [comment]
I guess i'm not skilled enough for that. I will let you looking into that if you think it's necessary to reduce the 20% gaps of Yellow. Red and Orange colours are barely used in the current scale.

Any good news on the .svg icons?

**Comment by LaxisB** [comment]
didn't get to it. today was busy with server migration. 
it's my next task though

**Comment by LaxisB** [comment]
just deployed the icons
