### ISSUE TITLE
Wrong layout on desktop when refreshing

### ISSUE THREAD

**Issue by NaughtyMuppet** [r6db/frontend#9]
How to reproduce:
* Search for a profile
* click the profile
* refresh

After refresh the profile seems to be in mobile layout and won't fix until you do some action (like start typing a new name into the search)

**Comment by LaxisB** [comment]
info for me: it seems like ElementQuery isn't refreshing properly on state change (same for hot reload)

**Comment by LaxisB** [comment]
@NaughtyMuppet pls check and reopen if needed
